import asyncio

from grpclib.client import Channel

# generated by protoc
from testsvc_pb2 import BinaryOpReq, BinaryOpResp
from testsvc_grpc import TestMathStub


async def main():
    channel = Channel('127.0.0.1', 19999)
    srvc = TestMathStub(channel)

    reply: BinaryOpResp = await srvc.Add(BinaryOpReq(i1=1,i2=1))
    print(reply.result)

    channel.close()


if __name__ == '__main__':
	loop = asyncio.get_event_loop()
	loop.run_until_complete(main())
    

