# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import EconomicalRegion_pb2 as EconomicalRegion__pb2


class EconomicalRegionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetEconomicalRegion = channel.unary_unary(
        '/EconomicalRegion/GetEconomicalRegion',
        request_serializer=EconomicalRegion__pb2.PSREQ.SerializeToString,
        response_deserializer=EconomicalRegion__pb2.PSRESP.FromString,
        )


class EconomicalRegionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetEconomicalRegion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EconomicalRegionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetEconomicalRegion': grpc.unary_unary_rpc_method_handler(
          servicer.GetEconomicalRegion,
          request_deserializer=EconomicalRegion__pb2.PSREQ.FromString,
          response_serializer=EconomicalRegion__pb2.PSRESP.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'EconomicalRegion', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
