# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import testsvc_pb2 as testsvc__pb2


class TestMathStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Mul = channel.unary_unary(
        '/TestMath/Mul',
        request_serializer=testsvc__pb2.BinaryOpReq.SerializeToString,
        response_deserializer=testsvc__pb2.BinaryOpResp.FromString,
        )
    self.Add = channel.unary_unary(
        '/TestMath/Add',
        request_serializer=testsvc__pb2.BinaryOpReq.SerializeToString,
        response_deserializer=testsvc__pb2.BinaryOpResp.FromString,
        )


class TestMathServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Mul(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestMathServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Mul': grpc.unary_unary_rpc_method_handler(
          servicer.Mul,
          request_deserializer=testsvc__pb2.BinaryOpReq.FromString,
          response_serializer=testsvc__pb2.BinaryOpResp.SerializeToString,
      ),
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=testsvc__pb2.BinaryOpReq.FromString,
          response_serializer=testsvc__pb2.BinaryOpResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TestMath', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
